export enum stepsNameEnum {
  FOR_WHO_STEP = "for-who-step",
  COFFEE_STEP = "coffee-step",
  JUICE_STEP = "juice-step",
  COOK_STEP = "cook-step",
  PARFUM_STEP = "parfum-step",
  SPICES_STEP = "spices-step",
  RANK_STEP = "rank-step",
  WHY_STEP = "why-step",
  EAT_WITH_STEP = "eat-with-step",
  MEAL_TYPE_STEP = "meal-type-step",
  MEAT_STEP = "meat-step",
  FISH_STEP = "fish-step",
  CHEESE_STEP = "cheese-step",
  BUDGET_STEP = "budget-step",
  WINE_TYPE_STEP = "wine-type-step",
}
